import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthPovider } from "@/context/authcontext";
import { UsersProvider } from "@/context/usersContext";
import { TasksProvider } from "@/context/tasksContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Taskmanager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthPovider>
        <UsersProvider>
        <TasksProvider>
        {children}
        </TasksProvider>
        </UsersProvider>
        </AuthPovider>
      </body>
      
    </html>
  );
}
