import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/authcontext";
import { UsersProvider } from "@/context/usersContext";
import { TasksProvider } from "@/context/tasksContext";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Taskmanager",
  description: "Generated by create next app",
};
/* <ThemeProvider 
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange>
              </ThemeProvider>
              */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <UsersProvider>
            <TasksProvider>
              {children}
            </TasksProvider>
          </UsersProvider>
        </AuthProvider>
      </body>
      
    </html>
  );
}
